config/routes.rb
SpiderTracker::Application.routes.draw do
	root 'spiders#index'
  resources :spiders
  

end

app/models/spider.rb
class Spider < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/spiders_controller.rb
class SpidersController < ApplicationController
	before_action :set_spider, only: [:show, :edit, :update, :destroy]

	def show
	end

	def index
		@spiders = Spider.all
	end

	def create
		@spider = Spider.new(spider_params)
		if @spider.save
			redirect_to @spider
		else
			render action: 'new'
		end
	end

	def new
		@spider = Spider.new
	end

	def update
		if @spider.update(spider_params)
			redirect_to @spider
		else
			render action: 'edit'
		end
	end

	def edit
	end

	def destroy
		@spider.destroy
		redirect_to spiders_url
	end

	private

	def set_spider
		@spider = Spider.find(params[:id])
	end

	def spider_params
		params.require(:spider).permit(:name, :origin, :terror, :habitat, :color, :poisonous, :weight, :image_url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpiderTracker</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spiders/_form.html.erb
<div class="new_spider">
	<div><%= form_for(@spider) do |f| %></div>
		<div><%= f.label :name %><%= f.text_field :name %></div>
		<div><%= f.label :poisonous %><%= f.check_box :poisonous %></div>
		<div><%= f.label :weight %><%= f.text_field :weight %></div>
		<div><%= f.label :origin %><%= f.text_field :origin %></div>
		<div><%= f.label :habitat %><%= f.text_field :habitat %></div>
		<div><%= f.label :color %><%= f.text_field :color %></div>
		<div><%= f.label :terror %><%= f.text_field :terror %></div>
		<div> <%= f.label :image_url %> <%= f.text_field :image_url %></div>
		<div> <%= f.submit %> </div>
	<% end %>
</div>

app/views/spiders/edit.html.erb
<h1>edit spider</h1>
<%= render 'form' %>

app/views/spiders/index.html.erb
<div class="spiders">
<% @spiders.each do |spider| %>
	<h3> <%= spider.name %> </h3>
	<%= image_tag spider.image_url, height: '32', width: '32' %>
	<%= link_to spider.name, spider %>
	Terror Level: <%= spider.terror %>
	<%= link_to "edit spider", edit_spider_path(spider) %>
	<%= link_to "destroy spider", spider, method: :delete, data:{confirm: "are you sure?"} %>
<% end %>
</div>

<%= link_to "New Spider", new_spider_path %>

<!-- button_to does post by default -->

app/views/spiders/new.html.erb
<h1>new spider</h1>
<%= render 'form' %>

app/views/spiders/show.html.erb
<div class="spider">
	<div> <%=@spider.name %></div>
	<div> <%=@spider.poisonous %></div>
	<div> <%=@spider.color %></div>
	<div> <%=@spider.weight %></div>
	<div> <%=@spider.terror %></div>
	<div> <%=@spider.habitat %></div>
	<div> <%=@spider.origin %></div>
	<div> <%= image_tag @spider.image_url %> </div>
</div>